# Generated by Django 5.0 on 2023-12-27 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Postapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'ordering': ['-updated_at'], 'verbose_name': 'CustomUser', 'verbose_name_plural': 'CustomUsers'},
        ),
        migrations.AddField(
            model_name='customuser',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(default='avatar.jpg', null=True, upload_to='media'),
        ),
    ]
